--名称
appname="米环看小说"
--版本号
appver="3.5.2"
--版本
appcode="1"
--SDK
appsdk="21"
--包名
packagename="com.AveQY.miui"
--调试模式
debugmode=true
--应用权限
user_permission={
  "ACCESS_NETWORK_STATE",
  "BIND_ACCESSIBILITY_SERVICE",
  "FOREGROUND_SERVICE",
  "GET_PACKAGE_SIZE",
  "INTERNET",
  "READ_EXTERNAL_STORAGE",
  "REQUEST_INSTALL_PACKAGES",
  "SYSTEM_ALERT_WINDOW",
  "WRITE_EXTERNAL_STORAGE",
  "WRITE_SETTINGS",
}
--跳过编译
skip_compilation={

}