require "import"
import "android.app.*"
import "android.os.*"
import "android.widget.*"
import "android.view.*"

import "function"

activity.setTheme(R.Theme_Teal)
layout={
  LinearLayout;
  layout_height="fill";
  layout_width="fill";
  backgroundColor=0xffffffff;
  orientation='vertical';
  {
    FrameLayout;
    layout_width='fill';
    layout_height='fill';
    {
      LinearLayout;
      orientation='vertical';
      layout_width='fill';
      layout_height='fill';
      {
        CardView;--卡片控件
        layout_width='fill';--卡片宽度
        CardBackgroundColor='#00000000';
        layout_height='24%h';
        elevation='0dp';--阴影属性
        id='title_',
        onClick=function()
          水珠动画(title_,500)
        end,
        {
          TextView;--文本控件
          layout_marginTop='50dp';--布局顶距
          layout_marginLeft='20dp';--布局左距
          layout_width='fill';--文本宽度
          layout_height='60dp';--文本高度
          gravity='';--重力属性
          textColor='#FF787679';--文字颜色
          text='欢迎来到';--显示的文字
          textSize='50sp';--文字大小
          --Typeface=Typeface.DEFAULT_BOLD;
        };
        {
          TextView;--文本控件
          layout_marginTop='120dp';--布局顶距
          layout_marginLeft='60dp';--布局左距
          layout_width='150dp';--文本宽度
          layout_height='60dp';--文本高度
          textColor='#FF787679';--文字颜色
          text='社区论坛';--显示的文字
          textSize='30sp';
        };
      },
      {
        LinearLayout;
        layout_width='fill';
        layout_height='fill';
        {
          LinearLayout;
          orientation='vertical';
          layout_width='50%w';
          layout_height='fill';
          gravity='center|top';
          {
            CardView;--卡片控件
            layout_marginTop='20dp';
            layout_margin='20dp';
            layout_gravity='';
            elevation='10dp';--阴影属性
            layout_width='140dp';--卡片宽度
            CardBackgroundColor='0xFF30877B';--卡片背景颜色
            layout_height='80dp';--卡片高度
            radius='15dp';
            id='qb',
            onClick=function()
              水珠动画(qb,500)
              activity.newActivity("forum/forum")
            end,
            {
              TextView;--文本控件
              layout_marginTop='40dp';--布局顶距
              layout_marginLeft='20dp';--布局左距
              layout_width='150dp';--文本宽度
              layout_height='60dp';--文本高度
              gravity='';--重力属性
              textColor='#FFffffff';--文字颜色
              text='#全部帖子#';--显示的文字
              textSize='15sp';
            };
          };
          --
          {
            CardView;--卡片控件
            layout_marginTop='20dp';
            layout_margin='20dp';--卡片边距
            layout_gravity='';--重力属性
            elevation='10dp';--阴影属性
            layout_width='140dp';--卡片宽度
            CardBackgroundColor='0xFF4F7DB6';--卡片背景颜色
            layout_height='80dp';--卡片高度
            radius='15dp';
            id='rj',
            onClick=function()
              水珠动画(rj,500)
              activity.newActivity("forum/forum",{"https://support.qq.com/embed/phone/413513/topic-detail/380/"})
            end,
            {
              TextView;--文本控件
              layout_marginTop='40dp';--布局顶距
              layout_marginLeft='20dp';--布局左距
              layout_width='150dp';--文本宽度
              layout_height='60dp';--文本高度
              gravity='';--重力属性
              textColor='#FFffffff';--文字颜色
              text='#实用软件#';--显示的文字
              textSize='15sp';
            };
          };
          {
            CardView;--卡片控件
            layout_marginTop='20dp';
            layout_margin='20dp';--卡片边距
            layout_gravity='';--重力属性
            elevation='10dp';--阴影属性
            layout_width='140dp';--卡片宽度
            CardBackgroundColor='0xFFA4815D';--卡片背景颜色
            layout_height='80dp';--卡片高度
            radius='15dp';
            id='zt',
            onClick=function()
              水珠动画(zt,500)
              activity.newActivity("forum/forum",{'https://support.qq.com/embed/phone/413513/topic-detail/377/'})
            end,
            {
              TextView;--文本控件
              layout_marginTop='40dp';--布局顶距
              layout_marginLeft='20dp';--布局左距
              layout_width='150dp';--文本宽度
              layout_height='60dp';
              textColor='#FFffffff';--文字颜色
              text='#休闲杂谈#';--显示的文字
              textSize='15sp';
            };
          };
        },

        {
          LinearLayout;
          orientation='vertical';
          layout_width='50%w';
          layout_height='fill';
          gravity='center|top';
          {
            CardView;--卡片控件
            layout_marginTop='20dp';
            layout_margin='20dp';--卡片边距
            layout_gravity='';--重力属性
            elevation='10dp';--阴影属性
            layout_width='140dp';--卡片宽度
            CardBackgroundColor='#ff575949';--卡片背景颜色
            layout_height='80dp';--卡片高度
            radius='15dp';
            id='fk',
            onClick=function()
              水珠动画(fk,500)
              activity.newActivity("forum/forum",{'https://support.qq.com/embed/phone/413513/topic-detail/376/'})
            end,
            {
              TextView;--文本控件
              layout_marginTop='40dp';--布局顶距
              layout_marginLeft='20dp';--布局左距
              layout_width='150dp';--文本宽度
              layout_height='60dp';
              textColor='#FFffffff';--文字颜色
              text='#反馈Bug#';--显示的文字
              textSize='15sp';
            };
          };
          --
          {
            CardView;--卡片控件
            layout_marginTop='20dp';
            layout_margin='20dp';--卡片边距
            layout_gravity='';--重力属性
            elevation='10dp';--阴影属性
            layout_width='140dp';--卡片宽度
            CardBackgroundColor='0xFFB0AE5B';--卡片背景颜色
            layout_height='80dp';--卡片高度
            radius='15dp';
            id='jl',
            onClick=function()
              水珠动画(jl,500)
              activity.newActivity("forum/forum",{'https://support.qq.com/embed/phone/413513/topic-detail/379/'})
            end,
            {
              TextView;--文本控件
              layout_marginTop='40dp';--布局顶距
              layout_marginLeft='20dp';--布局左距
              layout_width='150dp';--文本宽度
              layout_height='60dp';
              textColor='#FFffffff';--文字颜色
              text='#技术交流#';--显示的文字
              textSize='15sp';
            };
          };
          --
          --
          {
            CardView;--卡片控件
            layout_marginTop='20dp';
            layout_margin='20dp';
            elevation='10dp';--阴影属性
            layout_width='140dp';--卡片宽度
            CardBackgroundColor='#ff8f819a';
            layout_height='80dp';
            radius='15dp';
            layout_marginLeft='13dp';--布局左距
            id='jy',
            onClick=function()
              水珠动画(jy,500)
              activity.newActivity("forum/forum",{'https://support.qq.com/embed/phone/413513/topic-detail/378/'})
            end,
            {
              TextView;--文本控件
              layout_marginTop='40dp';--布局顶距
              layout_marginLeft='20dp';--布局左距
              layout_width='150dp';--文本宽度
              layout_height='60dp';--文本高度
              gravity='';--重力属性
              textColor='#FFffffff';--文字颜色
              text='#修改建议#';--显示的文字
              textSize='15sp';
            };
          };
        },
      };
    },

    {
      LinearLayout;
      orientation='vertical';
      layout_width='fill';
      gravity='center|bottom';
      layout_height='fill';
      {
        CardView;--卡片控件
        layout_width='fill';--卡片宽度
        CardBackgroundColor='#FF73AA95';
        layout_marginBottom='50dp';
        layout_margin='20dp';
        layout_width='80dp';
        layout_height='80dp';
        elevation='0dp';
        id='title_b',
        radius='360';
        onClick=function()
          水珠动画(title_b,500)
          activity.newActivity("forum/forum",{'https://support.qq.com/embed/phone/413513/new-post'})
        end,
        {
          ImageView;
          layout_height="30dp";
          layout_width="30dp";
          layout_gravity="center";
          colorFilter="#FFffff";
          src="icon/plus.png";
        },
      },
    },

  },
}

activity.setContentView(loadlayout(layout))
activity.ActionBar.hide()
状态栏()



