function 波纹特效v2(颜色)
  import"android.content.res.ColorStateList"
  return activity.Resources.getDrawable(activity.obtainStyledAttributes({android.R.attr.selectableItemBackground--[[Borderless]]}).getResourceId(0,0))
  .setColor(ColorStateList(int[0]
  .class{int{}},int{颜色 or 0x20000000}))
end
function tool_蓝奏云解析()
  import "android.graphics.Typeface"
  弹窗框架=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          TextView;
          layout_margin='2%w';
          gravity='center';
          layout_width='fill';
          layout_height='wrap';
          textColor='#ff757575';
          text="蓝奏云直链解析";
          textSize='18dp';
          typeface=Typeface.DEFAULT_BOLD,
        };
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height='60%w',
          background='#ffffffff',
          {
            TextView,
            layout_width="fill",
            layout_marginTop='2%w';
            text='链接：';
            layout_height="25dp",
            layout_gravity="center|left",
            textColor="0xFF757575",
            textSize='18dp';
          };
          {
            EditText;
            id="link",
            layout_width="80%w";
            layout_margin='5%w';
            singleLine=true;
            layout_gravity="center";
            background="0xFF000000",
          };
          {
            TextView,
            layout_width="fill",
            layout_marginTop='5%w';
            text='密码：';
            layout_height="20dp",
            layout_gravity="center|left",
            textColor="#ff555555",
            textSize='16dp';
          };
          {
            EditText;
            id="password",
            singleLine=true;
            layout_width="80%w";
            layout_gravity="center";
            layout_margin='5%w';
            background="0xFF000000",
          };
        };
        {
          TextView,
          layout_width="fill",
          layout_height="3px",
          layout_gravity="center",
          backgroundColor="#ffbebebe",
        };
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='解析';
              textSize='16dp';
              id="确认"
            };
          };
        };
      };
    };
  };

  xxx=AlertDialog.Builder(this)
  xxx.setView(loadlayout(弹窗框架))
  xxx=xxx.show()
  import "android.graphics.drawable.ColorDrawable"
  xxx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
  确认.onClick=function()
    if link.Text=="" then
      Toast.makeText(activity,"请输入链接", Toast.LENGTH_LONG).show()
     elseif password.Text=="" then
      Toast.makeText(activity,"请输入密码,暂不支持无密码\n我会尽快修复", Toast.LENGTH_LONG).show()
     else
      蓝奏云解析(link.Text,password.Text,function(url)import "android.content.Context" activity.getSystemService(Context.CLIPBOARD_SERVICE).setText(url) Toast.makeText(activity,"已复制直链", Toast.LENGTH_LONG).show() xxx.dismiss()end)
    end
  end;
  取消.onClick=function()
    xxx.dismiss()
  end;
  确认.foreground=波纹特效v2(0xFFCECECE)
  取消.foreground=波纹特效v2(0xFFCECECE)
end

function 保存桌面壁纸()
  import "android.graphics.Typeface"
  弹窗框架=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height='70%h',
          background='#ffffffff',
          {
            ImageView;
            id="drc",
            layout_width='wrap';
            layout_height='fill';
          };
        };
        {
          TextView,
          layout_width="fill",
          layout_height="3px",
          layout_gravity="center",
          backgroundColor="#ffbebebe",
        };
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='保存';
              textSize='16dp';
              id="确认"
            };
          };
        };
      };
    };
  };
  xxx=AlertDialog.Builder(this)
  xxx.setView(loadlayout(弹窗框架))
  xxx.setCancelable(false)
  xxx=xxx.show()
  import "android.graphics.drawable.ColorDrawable"
  xxx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
  zmimg=activity.getWallpaper()
  drc.setBackgroundDrawable(zmimg);
  确认.onClick=function()
    bm=drc.getDrawingCache()
    SavePicture("/storage/emulated/0/DCIM/Screenshots/Screenshot_桌面壁纸.png",bm)
    Toast.makeText(activity,"已保存到相册", Toast.LENGTH_LONG).show()
    xxx.dismiss()
  end;
  取消.onClick=function()
    xxx.dismiss()
  end;
  确认.foreground=波纹特效v2(0xFFCECECE)
  取消.foreground=波纹特效v2(0xFFCECECE)
end

function 查看网页源码(链接)
  import "android.graphics.Typeface"
  弹窗框架=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height='70%h';
          background='#ffffffff',
          {
            LuaWebView;
            layout_width="match_parent";
            id="Web";
            layout_height="match_parent";
          };
        };
        {
          TextView,
          layout_width="fill",
          layout_height="3px",
          layout_gravity="center",
          backgroundColor="#ffbebebe",
        };
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='保存';
              textSize='16dp';
              id="确认"
            };
          };
        };
      };
    };
  };
  弹窗框架2=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height='32%w',
          background='#ffffffff',
          {
            TextView,
            layout_width="fill",
            layout_margin='3%w',
            text='网页链接：';
            layout_height="25dp",
            layout_gravity="center|left",
            textColor="0xFF757575",
            textSize='18dp';
          };
          {
            EditText;
            id="link",
            layout_width="70%w";
            layout_margin='3%w';
            singleLine=true;
            layout_gravity="center";
            background="0xFF000000",
          };
        };
        {
          TextView,
          layout_width="fill",
          layout_height="3px",
          layout_gravity="center",
          backgroundColor="#ffbebebe",
        };
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消2"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='查看';
              textSize='16dp';
              id="确认2"
            };
          };
        };
      };
    };
  }
  xx=AlertDialog.Builder(this)
  xx.setView(loadlayout(弹窗框架2))
  xx=xx.show()
  import "android.graphics.drawable.ColorDrawable"
  xx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
  确认2.onClick=function()
    xx.dismiss()
    xxx=AlertDialog.Builder(this)
    xxx.setView(loadlayout(弹窗框架))
    xxx=xxx.show()
    xxx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
    Web.loadUrl('view-source:'..link.Text)
    确认.onClick=function()
      Http.download(link.Text,"/storage/emulated/0/米环看小说/工具/网页源码.html",function(code,data,cookie,header)
        提示('已保存到/storage/emulated/0/米环看小说/工具/')
        xxx.dismiss() end)
    end;
    取消.onClick=function()
      xxx.dismiss()
    end;
    确认.foreground=波纹特效v2(0xFFCECECE)
    取消.foreground=波纹特效v2(0xFFCECECE)
  end;
  取消2.onClick=function()
    xx.dismiss()
  end;
  确认2.foreground=波纹特效v2(0xFFCECECE)
  取消2.foreground=波纹特效v2(0xFFCECECE)
end

function 壁纸大全(图片链接,高度)
  import "android.graphics.Typeface"
  弹窗框架=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='center';
          orientation='vertical',
          layout_width='fill',
          layout_height=高度,
          background='#ffffffff',
          {
            ImageView;
            id="drc",
            layout_width='fill';
            layout_height='fill';
            src=图片链接,
          };
        };
        {
          TextView,
          layout_width="fill",
          layout_height="3px",
          layout_gravity="center",
          backgroundColor="#ffbebebe",
        };
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='保存';
              textSize='16dp';
              id="确认"
            };
          };
        };
      };
    };
  };
  xxx=AlertDialog.Builder(this)
  xxx.setView(loadlayout(弹窗框架))
  xxx.setCancelable(false)
  xxx=xxx.show()
  import "android.graphics.drawable.ColorDrawable"
  xxx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
  确认.onClick=function()
    Http.download(图片链接,"/storage/emulated/0/DCIM/Screenshots/"..os.time()..".png",function(code,data,cookie,header)
      提示('已保存到系统相册')
      xxx.dismiss() end)
  end;
  取消.onClick=function()
    xxx.dismiss()
  end;
  确认.foreground=波纹特效v2(0xFFCECECE)
  取消.foreground=波纹特效v2(0xFFCECECE)
end

function 网抑云热评()
  import "android.graphics.Typeface"
  function 加载()
    urla="https://api.4gml.com/NeteaseMusic?type=bq"
    Http.get(urla,nil,nil,nil,function(code,wy)
      歌名=wy:match("歌曲名：「&nbsp;(.-)&nbsp;」")
      评论者=wy:match("评论者：「&nbsp;(.-)&nbsp;」")
      评论内容=wy:match("『&nbsp;&nbsp;(.-)&nbsp;&nbsp;』")
      内容.setText("\n  歌曲名："..歌名.."\n\n  评论者："..评论者.."\n\n  评论内容："..评论内容..'\n')
    end)
  end
  弹窗框架=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height=高度,
          background='#ffffffff',
          {
            TextView;
            gravity="center|left|top";
            id="内容";
            text="";
            layout_width="match_parent";
            textColor="0xFF33AF89";
            textSize="15sp";
            layout_height="match_parent";
            textIsSelectable=true,
          };
        };
        {
          TextView,
          layout_width="fill",
          layout_height="3px",
          layout_gravity="center",
          backgroundColor="#ffbebebe",
        };
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='换一个';
              textSize='16dp';
              id="确认"
            };
          };
        };
      };
    };
  };
  xxx=AlertDialog.Builder(this)
  xxx.setView(loadlayout(弹窗框架))
  xxx.setCancelable(false)
  xxx=xxx.show()
  加载()
  import "android.graphics.drawable.ColorDrawable"
  xxx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
  确认.onClick=function()
    加载()
  end;
  取消.onClick=function()
    xxx.dismiss()
  end;
  确认.foreground=波纹特效v2(0xFFCECECE)
  取消.foreground=波纹特效v2(0xFFCECECE)
end

function 获取QQ头像()
  import "android.graphics.Typeface"
  弹窗框架=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height="wrap",
          background='#ffffffff',
          {
            CircleImageView;
            id="aa";
            src="";
            layout_height="120dp";
            layout_width="fill";
            layout_margin='8dp';
          };
        };
        {
          TextView,
          layout_width="fill",
          layout_height="3px",
          layout_gravity="center",
          backgroundColor="#ffbebebe",
        };
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='保存';
              textSize='16dp';
              id="确认"
            };
          };
        };
      };
    };
  };
  弹窗框架2=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height='32%w',
          background='#ffffffff',
          {
            TextView,
            layout_width="fill",
            layout_margin='3%w',
            text='QQ号：';
            layout_height="25dp",
            layout_gravity="center|left",
            textColor="0xFF757575",
            textSize='18dp';
          };
          {
            EditText;
            id="link",
            layout_width="70%w";
            layout_margin='3%w';
            singleLine=true;
            layout_gravity="center";
            background="0xFF000000",
            textColor="#FF808080",
          };
        };
        {
          TextView,
          layout_width="fill",
          layout_height="3px",
          layout_gravity="center",
          backgroundColor="#ffbebebe",
        };
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消2"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='查看';
              textSize='16dp';
              id="确认2"
            };
          };
        };
      };
    };
  }
  xx=AlertDialog.Builder(this)
  xx.setView(loadlayout(弹窗框架2))
  xx=xx.show()
  import "android.graphics.drawable.ColorDrawable"
  xx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
  确认2.onClick=function()
    k=link.Text
    if k=="" then
     else
      xx.dismiss()
      xxx=AlertDialog.Builder(this)
      xxx.setView(loadlayout(弹窗框架))
      xxx=xxx.show()
      m="http://q1.qlogo.cn/g?b=qq&nk="..k.."&s=100"
      aa.setImageBitmap(loadbitmap(m))
      xxx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
      确认.onClick=function()
        Http.download(图片链接,"/storage/emulated/0/DCIM/Screenshots/"..math.random(1,99)..'_'..math.random(1,99)..".png",function(code,data,cookie,header)
          提示('已保存到系统相册')
          xxx.dismiss() end)
      end;
      取消.onClick=function()
        xxx.dismiss()
      end;
      确认.foreground=波纹特效v2(0xFFCECECE)
      取消.foreground=波纹特效v2(0xFFCECECE)
    end
  end;
  取消2.onClick=function()
    xx.dismiss()
  end;
  确认2.foreground=波纹特效v2(0xFFCECECE)
  取消2.foreground=波纹特效v2(0xFFCECECE)
end

function 迷你英文()
  弹窗框架2=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height=高度,
          background='#ffffffff',
          {
            GridView,
            numColumns=5,
            layout_height='100%w',
            layout_width='80%w',
            id="grid",
          },
        };
        {
          TextView,
          layout_width="fill",
          layout_height="3px",
          layout_gravity="center",
          backgroundColor="#ffbebebe",
        };
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消2"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='复制所有';
              textSize='16dp';
              id="确认2"
            };
          };
        };
      };
    };
  }
  xx=AlertDialog.Builder(this)
  xx.setView(loadlayout(弹窗框架2))
  xx=xx.show()
  import "android.graphics.drawable.ColorDrawable"
  xx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
  item={
    TextView,
    layout_width="fill",
    layout_height="fill",
    TextSize="50",
    Gravity="center",
    id="tv",
  }
  data={}
  adp=LuaAdapter(activity,data,item)
  grid.setAdapter(adp)
  迷你={"ᴀ","ʙ","ᴄ","ᴅ","ᴇ","ғ","ɢ","ʜ","ɪ","ᴊ","ᴋ","ʟ","ᴍ","ɴ","ᴏ","ᴘ","ǫ","ʀ","s","ᴛ","ᴜ","ᴠ","ᴡ","x","ʏ","ᴢ"}
  for i=1,26 do
    table.insert(data,{tv=迷你[i]})
  end
  grid.onItemClick=function(l,v,p,i)
    写入剪切板(v.Text)
    提示("已复制"..v.Text)
  end

  确认2.onClick=function()
    写入剪切板("ᴀʙᴄᴅᴇғɢʜɪᴊᴋʟᴍɴᴏᴘǫʀsᴛᴜᴠᴡxʏᴢ")
    xx.dismiss()
    提示("已复制")
  end;
  取消2.onClick=function()
    xx.dismiss()
  end;
  确认2.foreground=波纹特效v2(0xFFCECECE)
  取消2.foreground=波纹特效v2(0xFFCECECE)
end

function 小时钟()
  import "android.animation.AnimatorSet"
  import "android.view.animation.Animation"
  import "android.view.animation.TranslateAnimation"
  import "android.view.animation.RotateAnimation"
  import "android.view.animation.AlphaAnimation"
  import "android.view.animation.ScaleAnimation"

  function Drawable_round(id,back,up,down)
    import "android.graphics.Color"
    import "android.graphics.drawable.GradientDrawable"
    if not up then
      up=25
    end
    if not down then
      down=up
    end
    id.setBackgroundDrawable(GradientDrawable()
    .setShape(GradientDrawable.RECTANGLE)
    .setColor(back)
    .setCornerRadii({up,up,up,up,down,down,down,down}))
  end
  Download_layout={
    LinearLayout;
    orientation="vertical";
    gravity='center',
    {
      TextView;
      layout_margin='20dp';
      layout_width='200dp';
      layout_height='200dp',
      gravity='center',
      textColor='#ff0000',
      id="tv";
    };
  };
  dialog=AlertDialog.Builder(this)
  .setView(loadlayout(Download_layout))
  .show()
  tv.background=LuaDrawable(function(c,p,d)
    p.setColor(0xff);
    p.setAntiAlias(true);
    p.setStrokeWidth(4);
    local b=d.bounds
    local W=b.right
    local H=b.bottom
    local mCircleWidth=0
    local r=math.min(W/2,H/2)
    p.setStyle(p.class.Style.STROKE)
    import "android.graphics.Paint"
    p.setStyle(Paint.Style.FILL);
    c.drawCircle(b.right/2,b.bottom/2,r,p)
    for i=0 ,60 do
      if(i==0 or i==15 or i==30 or i==45)then
        p.setStrokeWidth(3);
        p.setColor(0xff000000);
        p.setTextSize(25)
        c.drawLine(W/2,H/2-W/2+mCircleWidth/2,
        W/2,H/2-W/2+mCircleWidth/2+40,p);
        scaleTv=String.valueOf(tostring(tointeger(i==0 and 12 or i/5)));
        c.drawText(scaleTv,W/2-p.measureText(scaleTv)/2,
        H/2-W/2+mCircleWidth/2+80,p);
       elseif i==5 or i==10 or i==20 or i==25 or i==35 or i==40 or i==50 or i==55 then
        p.setStrokeWidth(2);
        p.setColor(0xff000000);
        c.drawLine(W/2,H/2-W/2+mCircleWidth/2,
        W/2,H/2-W/2+mCircleWidth/2+30,p);
        t=tostring(tointeger(i/5))
        scaleTv=String.valueOf(t);
        c.drawText(scaleTv,W/2-p.measureText(scaleTv)/2,
        H/2-W/2+mCircleWidth/2+75,p);
       else
        p.setColor(0xff000000);
        p.setStrokeWidth(1);
        c.drawLine(W/2,H/2-W/2+mCircleWidth/2,
        W/2,H/2-W/2+mCircleWidth+30,p);
      end
      c.rotate(6,W/2,H/2);
    end
    mCalendar=Calendar.getInstance();
    hours = mCalendar.get(Calendar.HOUR);
    minutes = mCalendar.get(Calendar.MINUTE);
    seconds=mCalendar.get(Calendar.SECOND);
    p.setStrokeCap(Paint.Cap.ROUND);
    c.save();
    p.setColor(0xFF1E1F22);
    p.setStrokeWidth(7);
    --这里计算时针需要旋转的角度 实现原理是计算出一共多少分钟除以60计算出真实的小时数（带有小数，为了更加准确计算度数），已知12小时是360度，现在求出了实际小时数比例求出角度
    hoursAngle = (hours * 60 + minutes) / 60 / 12 * 360;
    c.rotate(hoursAngle, W / 2, H / 2);
    c.drawLine(W / 2, H / 2 - W/2*0.5, W / 2, H/ 2 + W/2*0.15, p);
    c.restore();
    c.save();
    p.setColor(0xFF1E1F22);
    p.setStrokeWidth(5);
    --这里计算分针需要旋转的角度 60分钟360度，求出实际分钟数所占的度数
    minutesAngle =(minutes*60+seconds-60) / 60/ 60 * 360;
    c.rotate(minutesAngle, W/ 2, H/ 2);
    c.drawLine(W/ 2, H/ 2 - W/2*0.7, W / 2, H/ 2 + W/2*0.15, p);
    c.restore();
    --绘制秒针
    c.save();
    p.setColor(0xFF940000);
    p.setStrokeWidth(4);
    p.setStyle(Paint.Style.STROKE);
    --这里计算秒针需要旋转的角度 60秒360度，求出实际秒数所占的度数
    secondAngle = seconds/60*360;
    c.rotate(secondAngle, W / 2, H/ 2);
    c.drawLine(W/ 2, H / 2 - W/2*0.8, W/ 2, H / 2 + W/2*0.2, p);
    c.restore();
    --绘制中间的圆圈
    c.save();
    p.setColor(0xff000000);
    p.setStrokeWidth(6);
    p.setStyle(Paint.Style.FILL);
    c.drawCircle(W/2,H/2,10,p);
    c.restore();
    d.invalidateSelf()
  end)
  dialog.create()
  Drawable_round(dialog.getWindow(),0xFFffffff)
end

function 情话生成()
  function 加载()
    url="https://api.ooomn.com/api/love"
    Http.get(url,function(a,b)
      if a==200 then
        情话=b:match('(.+)')
        内容.setText(情话)
       else
        提示('请检查网络')
      end
    end)
  end
  弹窗框架=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height=高度,
          background='#ffffffff',
          {
            TextView;
            gravity="center|left|top";
            layout_margin='8dp';
            id="内容";
            text="";
            layout_width="match_parent";
            textColor="0xFFA55647";
            textSize="15sp";
            layout_height="match_parent";
            textIsSelectable=true,
          };
        };
        {
          TextView,
          layout_width="fill",
          layout_height="3px",
          layout_gravity="center",
          backgroundColor="#ffbebebe",
        };
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='换一个';
              textSize='16dp';
              id="确认"
            };
          };
        };
      };
    };
  };
  xxx=AlertDialog.Builder(this)
  xxx.setView(loadlayout(弹窗框架))
  xxx.setCancelable(false)
  xxx=xxx.show()
  加载()
  import "android.graphics.drawable.ColorDrawable"
  xxx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
  确认.onClick=function()
    加载()
  end;
  取消.onClick=function()
    xxx.dismiss()
  end;
  确认.foreground=波纹特效v2(0xFFCECECE)
  取消.foreground=波纹特效v2(0xFFCECECE)
end

function 小米运动刷步数()
  弹窗框架2=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height=高度,
          background='#ffffffff',
          {
            TextView,
            layout_width="fill",
            layout_margin='3%w',
            text='小米运动APP账号：';
            layout_height="25dp",
            layout_gravity="center|left",
            textColor="0xFF757575",
            textSize='18dp';
          };
          {
            EditText;
            id="link",
            layout_width="70%w";
            layout_margin='3%w';
            singleLine=true;
            layout_gravity="center";
            background="0xFF000000",
            textColor="#FF808080",
            Hint="不保存账号";
          };
          {
            TextView,
            layout_width="fill",
            layout_margin='3%w',
            text='账号密码：';
            layout_height="25dp",
            layout_gravity="center|left",
            textColor="0xFF757575",
            textSize='18dp';
          };
          {
            EditText;
            id="link2",
            layout_width="70%w";
            layout_margin='3%w';
            singleLine=true;
            layout_gravity="center";
            background="0xFF000000",
            textColor="#FF808080",
            Hint="不保存密码,不放心可以不用";
          };
        };
        {
          TextView,
          layout_width="fill",
          layout_margin='3%w',
          text='要刷的步数：';
          layout_height="25dp",
          layout_gravity="center|left",
          textColor="0xFF757575",
          textSize='18dp';
        };
        {
          EditText;
          id="link3",
          layout_width="70%w";
          layout_margin='3%w';
          singleLine=true;
          layout_gravity="center";
          background="0xFF000000",
          textColor="#FF808080",
          Hint="最大99999";
          InputType="number";
        };
        {
          TextView,
          layout_width="fill",
          layout_height="3px",
          layout_gravity="center",
          backgroundColor="#ffbebebe",
        };
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消2"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='开始';
              textSize='16dp';
              id="确认2"
            };
          };
        };
      };
    };
  }
  xx=AlertDialog.Builder(this)
  xx.setView(loadlayout(弹窗框架2))
  xx=xx.show()
  import "android.text.InputFilter"
  import "android.text.method.DigitsKeyListener"
  --限制输入个数
  link3.setFilters{InputFilter.LengthFilter(5)}
  import "android.graphics.drawable.ColorDrawable"
  xx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
  确认2.onClick=function()
    url="https://api.ooomn.com/api/mishua?do=shuabu&user="..link.Text.."&pass="..link2.Text.."&count="..link3.Text.."步"
    Http.get(url,function(a,b)
      if a==200 then
        返回数据=b:match('"msg": "(.-)"')
        提示(返回数据)
       else
      end
    end)
  end;
  取消2.onClick=function()
    xx.dismiss()
  end;
  确认2.foreground=波纹特效v2(0xFFCECECE)
  取消2.foreground=波纹特效v2(0xFFCECECE)
end

function 二维码生成()
  弹窗框架2=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height=高度,
          background='#ffffffff',
          {
            TextView,
            layout_width="fill",
            layout_margin='3%w',
            text='你想说的话：';
            layout_height="25dp",
            layout_gravity="center|left",
            textColor="0xFF757575",
            textSize='18dp';
          };
          {
            EditText;
            id="link",
            layout_width="70%w";
            layout_margin='3%w';
            singleLine=true;
            layout_gravity="center";
            background="0xFF000000",
            textColor="#FF808080",
            Hint="如:永远是有多远,你给我滚多远";
          };
        },
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消2"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='开始';
              textSize='16dp';
              id="确认2"
            };
          };
        };
      };
    };
  }
  xx=AlertDialog.Builder(this)
  xx.setView(loadlayout(弹窗框架2))
  xx=xx.show()
  import "android.graphics.drawable.ColorDrawable"
  xx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
  确认2.onClick=function()
    url="https://api.ooomn.com/api/qrcode?size=198&text="..link.Text
    Http.get(url,function(a,b)
      if a==200 then
        壁纸大全(url)
       else
      end
    end)
  end;
  取消2.onClick=function()
    xx.dismiss()
  end;
  确认2.foreground=波纹特效v2(0xFFCECECE)
  取消2.foreground=波纹特效v2(0xFFCECECE)
end

function 强制QQ聊天(号码)
  弹窗框架2=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height=高度,
          background='#ffffffff',
          {
            TextView,
            layout_width="fill",
            layout_margin='3%w',
            text='对象QQ：';
            layout_height="25dp",
            layout_gravity="center|left",
            textColor="0xFF757575",
            textSize='18dp';
          };
          {
            EditText;
            id="link",
            layout_width="70%w";
            layout_margin='3%w';
            singleLine=true;
            layout_gravity="center";
            background="0xFF000000",
            textColor="#FF808080",
            Hint="";
          };
        },
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消2"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='开始';
              textSize='16dp';
              id="确认2"
            };
          };
        };
      };
    };
  }
  xx=AlertDialog.Builder(this)
  xx.setView(loadlayout(弹窗框架2))
  xx=xx.show()
  import "android.graphics.drawable.ColorDrawable"
  xx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
  确认2.onClick=function()
    if link.Text=="" then
     else
      QQ聊天(link.Text)
    end
  end;
  取消2.onClick=function()
    xx.dismiss()
  end;
  确认2.foreground=波纹特效v2(0xFFCECECE)
  取消2.foreground=波纹特效v2(0xFFCECECE)
end

function 翻译()
  弹窗框架2=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height=高度,
          background='#ffffffff',
          {
            TextView,
            layout_width="fill",
            layout_margin='3%w',
            text='中文：(默认)';
            layout_height="25dp",
            layout_gravity="center|left",
            textColor="0xFF757575",
            textSize='18dp';
          };
          {
            EditText;
            id="link",
            layout_width="70%w";
            layout_margin='3%w';
            singleLine=true;
            layout_gravity="center";
            background="0xFF000000",
            textColor="#FF808080",
            Hint="可留空";
          };
          {
            TextView,
            layout_width="fill",
            layout_margin='3%w',
            text='英文：';
            layout_height="25dp",
            layout_gravity="center|left",
            textColor="0xFF757575",
            textSize='18dp';
          };
          {
            EditText;
            id="link2",
            layout_width="70%w";
            layout_margin='3%w';
            singleLine=true;
            layout_gravity="center";
            background="0xFF000000",
            textColor="#FF808080",
            Hint="可留空";
          };
        },
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='清空';
              textSize='16dp';
              id="取消2"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='开始';
              textSize='16dp';
              id="确认2"
            };
          };
        };
      };
    };
  }
  xx=AlertDialog.Builder(this)
  xx.setView(loadlayout(弹窗框架2))
  xx=xx.show()
  import "android.graphics.drawable.ColorDrawable"
  xx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
  确认2.onClick=function()
    if link.Text=="" then
      if link2.Text=="" then
        Toast.makeText(activity,"请输入", Toast.LENGTH_LONG).show()
       else
        url="https://api.ooomn.com/api/fy?q="..link2.Text.."&to=zh"
        Http.get(url,function(a,b)
          link.setText(b:match('dst": "(.-)"'))
        end)
      end
     else
      url="https://api.ooomn.com/api/fy?q="..link.Text.."&to=en"
      Http.get(url,function(a,b)
        link2.setText(b:match('dst": "(.-)"'))
      end)
    end
  end;
  取消2.onClick=function()
    link.setText("")
    link2.setText("")
  end;
  确认2.foreground=波纹特效v2(0xFFCECECE)
  取消2.foreground=波纹特效v2(0xFFCECECE)
end

function 彩色群昵称()
  弹窗框架2=
  {
    LinearLayout,
    orientation='vertical',
    layout_width='fill',
    layout_height='wrap',
    background='#00FFFFFF',
    {
      CardView;
      layout_margin='8dp';
      layout_gravity='center';
      elevation='5dp';
      layout_width='80%w';
      layout_height='fill';
      CardBackgroundColor='0xfffFFFFF';
      radius='10dp';
      {
        LinearLayout,
        gravity='center';
        orientation='vertical',
        layout_width='fill',
        layout_height='wrap';
        background='0xFF4AB199',
        {
          LinearLayout,
          layout_padding='10%';
          gravity='left|top';
          orientation='vertical',
          layout_width='fill',
          layout_height=高度,
          background='#ffffffff',
          {
            LinearLayout;
            layout_height="fill";
            layout_width="fill";
            gravity="center";
            {
              LinearLayout;
              layout_height="80dp";
              layout_width="fill";
              orientation="vertical";
              {
                LinearLayout;
                layout_height="80dp";
                layout_width="match_parent";
                orientation="horizontal";
                gravity="center";
                {
                  EditText;
                  layout_marginTop="10dp";
                  layout_width="150dp";
                  hint="请输入昵称";
                  textSize="15sp";
                  id="昵称";
                  singleLine=true;
                  layout_gravity="center";
                  background="0xFF000000",
                };
                {
                  Spinner;
                  layout_marginLeft="10dp";
                  layout_marginTop="9dp",
                  items={
                    "黄色";
                    "绿色";
                    "蓝色";
                    "紫色";
                    "粉色";
                    "红色";
                    "黑色";
                    "朝夕";
                    "潮流";
                    "粉黛";
                    "夜空";
                    "晚秋";
                    "糖果缤纷";
                    "盛夏";
                    "日出";
                    "霓虹闪烁";
                    "马卡龙";
                    "科技感";
                    "黄昏";
                    "高级灰";
                    "冬梅";
                    "初春";
                  };
                  id="类型";
                  layout_gravity="center";
                };
              };
            };
          };
        },
        {
          LinearLayout,
          orientation='horizontal',
          layout_width='fill',
          layout_height='13%w',
          background='#00FFFFFF',
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00FFFFFF',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='#ff757575';
              text='关闭';
              textSize='16dp';
              id="取消"
            };
          };
          {
            TextView,
            layout_width="3px",
            layout_height="fill",
            layout_gravity="center",
            backgroundColor="#ffbebebe",
          };
          {
            LinearLayout,
            orientation='vertical',
            layout_width='40%w',
            layout_height='fill',
            background='#00000000',
            {
              TextView;
              gravity='center';
              layout_width='fill';
              layout_height='fill';
              textColor='0xFF33AF89';
              text='生成';
              textSize='16dp';
              id="确认"
            };
          };
        };
      };
    };
  }
  xx=AlertDialog.Builder(this)
  xx.setView(loadlayout(弹窗框架2))
  xx.setCancelable(false)
  xx=xx.show()
  import "android.graphics.drawable.ColorDrawable"
  xx.getWindow().setBackgroundDrawable(ColorDrawable(0x00000000))
  类型.onItemSelected=function(l,v,p,i)
    选择类型=v.text
  end
  function 事_件(彩色)
    写入剪切板(彩色..昵称.Text)
    提示("直接去群内粘贴昵称")
    xx.dismiss()
  end
  确认.onClick=function()
    if 选择类型=="黄色" then
      事_件("<&ÿÿÏP>")
     elseif 选择类型=="绿色" then
      事_件("<&ÿ␇ÄW>")
     elseif 选择类型=="蓝色" then
      事_件("<&ÿ␇Çý>")
     elseif 选择类型=="紫色" then
      事_件("<&ÿÒUÐ>")
     elseif 选择类型=="粉色" then
      事_件("<&ÿÿ]•>")
     elseif 选择类型=="红色" then
      事_件("<&ÿÿ5@>")
     elseif 选择类型=="黑色" then
      事_件("<&ÿĀĀĀ>")
     elseif 选择类型=="朝夕" then
      事_件("<%ĀĀ␇Ý>")
     elseif 选择类型=="潮流" then
      事_件("<%ĀĀ␇Þ>")
     elseif 选择类型=="粉黛" then
      事_件("<%ĀĀ␇Ü>")
     elseif 选择类型=="夜空" then
      事_件("<%ĀĀÛ>")
     elseif 选择类型=="晚秋" then
      事_件("<%ĀĀ␇Ú>")
     elseif 选择类型=="糖果缤纷" then
      事_件("<%ĀĀ␇Ù>")
     elseif 选择类型=="盛夏" then
      事_件("<%ĀĀ␇Ø>")
     elseif 选择类型=="日出" then
      事_件("<%ĀĀ␇×>")
     elseif 选择类型=="霓虹闪烁" then
      事_件("<%ĀĀ␇Ö>")
     elseif 选择类型=="马卡龙" then
      事_件("<%ĀĀ␇Õ>")
     elseif 选择类型=="科技感" then
      事_件("<%ĀĀ␇Ô>")
     elseif 选择类型=="黄昏" then
      事_件("<%ĀĀ␇Ù>")
     elseif 选择类型=="高级灰" then
      事_件("<%ĀĀ␇Ù>")
     elseif 选择类型=="冬梅" then
      事_件("<%ĀĀ␇Ù>")
     elseif 选择类型=="初春" then
      事_件("<%ĀĀ␇Ù>")
    end
  end;
  取消.onClick=function()
    xx.dismiss()
  end;
  确认.foreground=波纹特效v2(0xFFCECECE)
  取消.foreground=波纹特效v2(0xFFCECECE)
end